language: scala

scala:
  - "2.11.7"

branches:
  only:
    - master
    - 2.11.x

jdk:
  - oraclejdk8

sudo: false

notifications:
  email:
    recipients:
      - marko@mentat-labs.com

services: redis-server
